Add "Parallel Select (Anime)"
ProjectIgnis/CardScripts pull request #1051
Opened 2023-07-15 14:03 UTC by idk-what-to-name-here

https://yugipedia.com/wiki/Parallel_Select_(anime)

- [X] I am following the [contributing guidelines](https://github.com/ProjectIgnis/CardScripts/blob/master/CONTRIBUTING.md).
- [X] I am making the [changes to modernize the scripts](https://github.com/ProjectIgnis/CardScripts/blob/master/MODERNIZING.md).

**New card checklist**

- [X] I have submitted a corresponding database entry for [BabelCDB](https://github.com/ProjectIgnis/BabelCDB/blob/master/README.md) according to its guidelines. Link to the pull request: _https://github.com/larry126/BabelCDB/pull/126_
- [X] This card is not marked with a reason to not be added in the unofficial card tracker in `#card-scripting-101`.
Supervising staff member(s): _@larry126_

2023-07-22 07:00 UTC, larry126 requested changes

2023-07-22 12:38 UTC, idk-what-to-name-here commented
done

2023-07-23 04:15 UTC, larry126 requested changes
And where have the card names gone? xD

2023-07-23 04:15 UTC, larry126 commented on unofficial/c511027651.lua
> +	e1:SetCategory(CATEGORY_DRAW)
You still need CATEGORY_TOHAND since you are adding something to your hand other than via drawing

2023-07-23 11:42 UTC, idk-what-to-name-here commented
done

2023-07-24 05:28 UTC, larry126 approved these changes

2023-07-24 05:28 UTC, merged